### ISSUE TITLE
[Github] Add Linting Rules and Issue Template to Github

### ISSUE THREAD

**Issue by dreulavelle** [rivenmedia/riven#135]

**Comment by AyushSehrawat** [comment]
Add prettier and black, eslint is pretty strict 😔

**Comment by dreulavelle** [comment]
Its been on my list, but distracted from other features and things that have taken up my time lol.. if you wannaadd them that'd be great lol.. if you have time

**Comment by AyushSehrawat** [comment]
@dreulavelle Close as done
