### ISSUE TITLE
[Feature] New scraper service: MediaFusion

### ISSUE THREAD

**Issue by balajiselva** [rivenmedia/riven#151]
Can you please add this scraper for regional content https://github.com/mhdzumair/MediaFusion.

**Comment by dreulavelle** [comment]
I was looking at it a little bit, does it have an api and support external id's like imdb ?

**Comment by dreulavelle** [comment]
Oh its a stremio addon, yeah I can support this. I'll put it on the todo list. :)

**Comment by balajiselva** [comment]
Thanks 😊
