### ISSUE TITLE
Reinitialization onboarding bug

### ISSUE THREAD

**Issue by Gaisberg** [rivenmedia/riven#168]
If initialization of any service fails with correct settings, f/e overseerr hasnt been started it will never reinitialize the service because we dont change settings. This needs to be addressed

**Comment by AyushSehrawat** [comment]
What should we do about it ? I was thinking some way to detect the difference and then either show user pop up / notification regarding it

**Comment by AyushSehrawat** [comment]
closing as i will only be looking for symlink from now on
