### ISSUE TITLE
[Feature] multiple Plex accounts

### ISSUE THREAD

**Issue by hjongedijk** [rivenmedia/riven#171]
Option to have multiple Plex accounts in Iceberg to check multiple watchlists and add a label e.g. From: username1, From: username2

With this feature you can have multiple Plex accounts using the same Plex server and the users only sees the media that has the label of the user in it.

As example for config in frontend

Users:
username1
username1 token

username2
username2 token

Things that needs to be done on background of Iceberg.

Check the Plex watchlist of configured users and check if media is already present, when present add label "From: username1" or "From: username2" to media, when there is already a label on the label just add the new one behind it. When media isnt present download the media and add the label of the user which added the media on the watchlist. Rinse and repeat.

When you have more questions about this, contact XBG The Killer on the Discord.

Example of the labels:

Labels configured for multiple users: (media added on multiple watchlist Plex accounts)
![image](https://github.com/dreulavelle/iceberg/assets/2362834/655fd595-29e4-4e07-8150-972428d1c6ad)

Single Plex user who added it on watchlist
![image](https://github.com/dreulavelle/iceberg/assets/2362834/271b1f4f-dbbb-4e28-b8eb-42c5497db47d)

**Comment by dreulavelle** [comment]
Putting this here for myself. This is how itsToggle (plex_debrid) handled Labels

- https://github.com/itsToggle/plex_debrid/blob/a7c3efbcee6c4e9b47e5a1b7c2510c10f69c5c50/content/services/plex.py#L532
