### ISSUE TITLE
[Feature] Enhancement Ideas

### ISSUE THREAD

**Issue by godver3** [rivenmedia/riven#2]
I’m just going to throw various ideas out there:
* The obvious stuff like Trakt/MDBlist support, Overseerr support
* Content tracking - the software should not only check for content availability in Plex (ie if something becomes unavailable and Zurg can’t fix it, leading to the item being removed, Iceburg should re-search for the item) but also track availability per version
  * Meaning if the 4k version that was requested goes down, Iceburg searches for the 4k version even if a 1080p version remains available
* Search logic - only search versions that are available (ie only search a 4k version if that content was released in 4k)
* Ignore flow - it would be great to periodically unignore when items are considered available to avoid early searches ignoring items
  * Arrs flow - possible idea that if an item cannot be found but is considered available that some form of Usenet workflow is supported (could simply be if S03E05 is not found, the ignored item is marked as requested in Sonarr)
* Notifications - on release snatch, on item added etc
* Continuing series flag - flag items as either continuing or not to ensure that a series that resumes airing continues to pull new content

**Comment by Gaisberg** [comment]
Good news, as of now:
- mdblist and overseerr content services are implement
- the way the app is built versioning should be easy to implement
- Ignore flow is implemented as you described but needs to be improved
- Continuing series flag is implemented

For the rest good ideas!
