### ISSUE TITLE
Implement file watching service to emit delete events when symlinks are deleted

### ISSUE THREAD

**Issue by omnunum** [rivenmedia/riven#231]
When a user deletes something in Plex, plex will delete the symlink, and we need to be able to detect this to delete the container item for it.

**Comment by dreulavelle** [comment]
Added this feature in https://github.com/dreulavelle/iceberg/pull/224/commits/514ef4c9d5596382307478abd844ca6534e8572a

**Comment by dreulavelle** [comment]
I left a couple notes and todo's in there for myself.

Here's what its doing,

![image](https://github.com/dreulavelle/iceberg/assets/5782630/db47ba06-2cf3-49d1-b2e2-7dec201ad0e3)

**Comment by dreulavelle** [comment]
This needs to be redone as that feature got removed a while back as it was causing issues on some OS architectures.
