### ISSUE TITLE
[Feature] Discord notifications via webhook for Plex Watchlist changes

### ISSUE THREAD

**Issue by TheIndieArmy** [rivenmedia/riven#283]
A feature allowing the user to setup Discord notifications for changes to user's Plex Watchlist. This is helpful to Plex server admin in ensuring the content their users are watchlisting (requesting) is being picked up in a timely manner. Or if it needs to be obtained through other means. 

The attached file is some code written with ChatGPT that I've been using successfully for some time.
[watchlist_notifier.txt](https://github.com/dreulavelle/iceberg/files/14939999/watchlist_notifier.txt)

Mercury also created a PD fork here with the feature: https://github.com/mercuryy-1337/plex_debrid

**Comment by dreulavelle** [comment]
I was thinking of adding shoutrrr support 🤔

**Comment by TheIndieArmy** [comment]
I'm not familiar with Shoutrrr, I'll have to take a look at it. I'm using Notifiarr and the ChatGPT script I created to fill in the gap.

**Comment by AyushSehrawat** [comment]
Will we need discord notifications if frontend gets it's own notification ? @dreulavelle

**Comment by dreulavelle** [comment]
people keep asking about discord notifications.. so I guess I'll add it.. but I think it will get pretty spammy.. so I was thinking to do it in the form of reports? Like maybe every few hours, or nightly report or something?

**Comment by AyushSehrawat** [comment]
> people keep asking about discord notifications.. so I guess I'll add it.. but I think it will get pretty spammy.. so I was thinking to do it in the form of reports? Like maybe every few hours, or nightly report or something?

Like a background service ? Will be nice, user can set the report interval and webhook url in settings, which can be edited in frontend too.

**Comment by dreulavelle** [comment]
This is completed. Take a look at the notifications settings in the settings.json file. In the service urls, you can add your discord webhook.

Heres what mine looks like as an example,
```json
    "notifications": {
        "enabled": true,
        "title": "Riven completed something!",
        "on_item_type": [
            "movie",
            "show",
            "season"
        ],
        "service_urls": [
            "discord://xxxxx/xxxxxxxxxxxxxxxxxxx"
        ]
    },
```
