### ISSUE TITLE
Plex library check

### ISSUE THREAD

**Issue by deepvalu** [rivenmedia/riven#362]
Check Plex library before scraping.

**Comment by dreulavelle** [comment]
The "Library" is the symlinks, if a symlink doesnt exist, then we scrape.

**Comment by deepvalu** [comment]
Boo! I will pay you 50 dollars to make it an option.

**Comment by dreulavelle** [comment]
As much as I'd love to take your money lol, this option would be redundant since we already check the Symlink Library. Theres just no point in checking both. 

Why check Plex when we can go to the "source" to see if the file is even there? ;)

**Comment by deepvalu** [comment]
Because I use other tools to add content. I might want a local copy or use debris media manger to pick a specific quality for only one movie. Also it saves me the time of having to backfill my current library.

**Comment by dreulavelle** [comment]
Hmm.. 

What would you want it to do, or look like? User settings?

**Comment by deepvalu** [comment]
Ideally a toggle to choose whether or not Riven uses the symlink library or plex library as the source of truth.

**Comment by dreulavelle** [comment]
oof lol.. 

@Gaisberg

**Comment by dreulavelle** [comment]
switching source of truth's like that is a recipe for disaster I feel like..

**Comment by deepvalu** [comment]
How so? If you switched couldn't you just rebuild the database?

**Comment by dreulavelle** [comment]
I suppose we could drop the tables and rebuild

**Comment by AyushSehrawat** [comment]
> switching source of truth's like that is a recipe for disaster I feel like..

True
