### ISSUE TITLE
Results not being passed to iceberg from some trackers in Jackett

### ISSUE THREAD

**Issue by smeep23** [rivenmedia/riven#363]
I have Jackett setup and working properly with iceberg and it returns results, but some trackers (public and private) return results in Jackett but they never make it to iceberg.

Jackett log: 
2024-06-09 08:00:38 | Info | Torznab search in Torlock for Shrek Forever After => Found 99 releases [1077ms]

Iceberg log:
2024-06-09 12:00:38 | 🤖 DEBUG     | jackett._thread_target - Scraped Shrek Forever After from Torlock in 1.23 seconds with 0 results

I have seen this behavior from iptorrents and torlock. There are others but I did not note them at the time.

**Comment by krishne35** [comment]
same problem here with 1337x and many other where jackett does get links but riven says 0 results
`riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from RuTor in 0.01 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from Solid Torrents in 0.01 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from EZTV in 0.00 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from SubsPlease in 0.03 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from 1337x in 0.02 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from The Pirate Bay in 0.03 seconds with 39 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from Torlock in 0.13 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from TorrentFunk in 0.12 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from TheRARBG in 0.14 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from GloDLS in 0.02 seconds with 24 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from TorrentLeech in 0.03 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from YTS in 0.02 seconds with 3 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._fetch_results - Indexer failed to fetch results for movie: kickasstorrents.to
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from kickasstorrents.to in 0.52 seconds with 0 results
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._fetch_results - Indexer failed to fetch results for movie: LimeTorrents
riven           | 24-08-07 00:59:31 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from LimeTorrents in 0.76 seconds with 0 results
riven           | 24-08-07 00:59:56 | 👾 API       | main.dispatch - GET / - 200 - 0.00s
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | jackett._fetch_results - Indexer failed to fetch results for movie: Nyaa.si
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | jackett._thread_target - Scraped Deadpool from Nyaa.si in 30.02 seconds with 0 results
riven           | 24-08-07 01:00:01 | 👻 SCRAPER   | jackett.scrape - Found 61 streams out of 66 for Deadpool
riven           | 24-08-07 01:00:01 | 👻 SCRAPER   | shared._parse_results - Processing 61 results for Deadpool
riven           | 24-08-07 01:00:01 | 👻 SCRAPER   | shared._parse_results - Processed 16 matches for Deadpool
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 254 and ratio 1.00: 'Deadpool.2016.RERIP.PROPER.1080p.BluRay.H264.AAC-LAMA[TGx]'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 252 and ratio 1.00: 'Deadpool 2016 Complete (1080p Bluray x265 10bit AAC 7.1 Joy)[UTR'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 240 and ratio 1.00: 'Deadpool.2016.1080p.WEB.DL.H264.AC3.EVO'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 240 and ratio 1.00: 'Deadpool 2016 1080p HC HDRip X264 AC3-EVO'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 230 and ratio 1.00: 'Deadpool (2016) 1080p BluRay 5.1Ch AC3 x264 SUJAIDR'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 210 and ratio 1.00: 'Deadpool.2016.720p.HC.HDRip.x264.AAC-ETRG'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 190 and ratio 1.00: 'Deadpool.2016.720p.WEB.DL.H264.AC3.EVO'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 180 and ratio 1.00: 'Deadpool (2016) 1080p BluRay 5.1Ch x264 SUJAIDR'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 180 and ratio 1.00: 'Deadpool (2016) 1080p BluRay - 6CH - 2GB -ShAaNiG'
riven           | 24-08-07 01:00:01 | 🤖 DEBUG     | __init__.scrape - [Movie] Parsed 'Deadpool' with rank 150 and ratio 1.00: 'Deadpool (2016) [Ryan Reynolds] 1080p H264 DolbyD 5 1 & nickarad'
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program._remove_from_running_items - Item Deadpool finished running section Scraping
riven           | 24-08-07 01:00:01 | 🔍 DISCOVERY | program._push_event_queue - Re-added Deadpool to the queue
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program._process_future_item - Service Scraping finished running on Deadpool
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program.add_to_running - Item tt1431045 started running section program.run
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program._remove_from_running_items - Item tt1431045 finished running section program.run
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program.add_to_running - Item Deadpool started running section Downloader
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program._submit_job - Submitting service Downloader to the pool with Deadpool
riven           | 24-08-07 01:00:01 | 🔗 DEBRID    | realdebrid.is_cached - Processing 16 streams for Deadpool
riven           | 24-08-07 01:00:01 | 🤖 PROGRAM   | program._process_future_item - Service Overseerr finished running.
riven           | 24-08-07 01:00:04 | 🤷‍ NOT_FOUND | realdebrid.is_cached - No wanted cached streams found for Deadpool out of 16
riven           | 24-08-07 01:00:04 | 🤖 PROGRAM   | program._remove_from_running_items - Item Deadpool finished running section Downloader
riven           | 24-08-07 01:00:04 | 🔍 DISCOVERY | program._push_event_queue - Re-added Deadpool to the queue
riven           | 24-08-07 01:00:04 | 🤖 PROGRAM   | program._process_future_item - Service Downloader finished running on Deadpool
`
jacket logs

`Torznab search in YTS for Deadpool => Found 3 releases (from cache) [0ms]
2024-08-07 00:59:31	Info	
Torznab search in TorrentLeech for Deadpool => Found 35 releases (from cache) [7ms]
2024-08-07 00:59:31	Info	
Torznab search in GloDLS for Deadpool => Found 24 releases (from cache) [1ms]
2024-08-07 00:59:31	Info	
Torznab search in TheRARBG for Deadpool => Found 37 releases (from cache) [2ms]
2024-08-07 00:59:31	Info	
Torznab search in TorrentFunk for Deadpool => Found 42 releases (from cache) [2ms]
2024-08-07 00:59:31	Info	
Torznab search in Torlock for Deadpool => Found 100 releases (from cache) [4ms]
2024-08-07 00:59:31	Info	
Torznab search in 1337x for Deadpool => Found 36 releases (from cache) [2ms]
2024-08-07 00:59:31	Info	
Torznab search in The Pirate Bay for Deadpool => Found 39 releases (from cache) [0ms]
2024-08-07 00:59:31	Info	
Torznab search in Solid Torrents for Deadpool => Found 0 releases (from cache) [0ms]
2024-08-07 00:59:31	Info	
Torznab search in RuTor for Deadpool => Found 0 releases (from cache) [0ms]
2024-08-07 00:59:31	Info	
Torznab search in SubsPlease for Deadpool => Found 0 releases (from cache) [0ms]`

**Comment by dreulavelle** [comment]
Please dont forget to format. As it really makes a difference in reading the logs..

What version are you running on?

**Comment by krishne35** [comment]
Riven logs : https://pastebin.com/VVZergcB

Jackett log:
![Screenshot_2024-08-07-07-21-58-79_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/user-attachments/assets/4fa54129-1bb1-4c44-9752-d382f0a7b327)

I'm running latest 0.9.2


Sorry though github does the format automatically
