### ISSUE TITLE
Iceberg user getting created with the wrong permissions 

### ISSUE THREAD

**Issue by dextrous0z** [rivenmedia/riven#374]
Investigated into this issue a little bit,

I've consoled into the docker here's the current id of the icerberg user 

/iceberg # id iceberg
uid=1000(iceberg) gid=1000(iceberg) groups=1000(iceberg),1000(iceberg)
/iceberg # echo $PGID
100
/iceberg #

**Comment by dreulavelle** [comment]
PGID is not an accurate representation of the user id.. you should use `id` or `cat /etc/passwd` to get user id and group id..

that being said.. I might of broke the puid/pgid when I was messing with the terminal coloring lmao. I'll take a look at this!

**Comment by dextrous0z** [comment]
I've got a fix for this want me to add it to the pull request, I've currently got open ? 

It is a issue for user's with different default $PUID, $PGID for example on unraid we use 99:100 
Leading to issues with deleting symlink folders as they are getting created with 1000 permissions,as plex is running with 99:100 permissions. 

drwxr-xr-x 1 User 1000  18 Jun 10 09:20 Dark\ Matter\ (2024)\ {tt19231492}/

**Comment by dreulavelle** [comment]
```yml
    environment:
      - PUID=1000
      - PGID=1000
```
Did you set the env variables by chance? And your saying setting those didn't work?

**Comment by dextrous0z** [comment]
Yeah I've had the environment variables set 

    environment:
      - PUID=99
      - PGID=100 
      
Running Iceberg showed this in the log still lead to the files being created with 1000 permissions: 

Starting Container with 99:100 permissions...
Container Initialization complete.
Starting backend...
Starting frontend...
Listening on 0.0.0.0:3000

**Comment by dreulavelle** [comment]
well shit.. lol.. then yeah.. thats definitely broken haha

**Comment by dextrous0z** [comment]
I worked this up and I think it might have solved the issue: 

Leads to this folder getting created: 

drwxr-xr-x 1 nobody users  72 Jun 10 10:19 Hit\ Man\ (2024)\ {imdb-tt20215968}/

##This change in the entrypoint.sh

# Check if the user exists and has the correct UID
if getent passwd $USERNAME > /dev/null
    set existing_uid (getent passwd $USERNAME | cut -d: -f3)
    if test $existing_uid != $PUID
        usermod -u $PUID $USERNAME
        if test $status -ne 0
            echo "Failed to modify user UID. Exiting..."
            exit 1
        end
    end
else
    adduser -D -u $PUID -G $GROUPNAME $USERNAME
    if test $status -ne 0
        echo "Failed to create user. Exiting..."
        exit 1
    end
end

# Ensure the user is in the correct group
usermod -g $GROUPNAME $USERNAME
if test $status -ne 0
    echo "Failed to set group $GROUPNAME for user $USERNAME. Exiting..."
    exit 1
end

**Comment by dreulavelle** [comment]
I'll use my old code for it. It was working correctly before I effed it up lol

**Comment by dreulavelle** [comment]
Ah okay, make a pr, or add it to your current open one!

**Comment by dextrous0z** [comment]
Hey new build fixed the issue should be good to close this off

**Comment by Jeor** [comment]
@dextrous0z Did you just deploy the stack via docker compose in unraid? Having issues getting mine setup.
