### ISSUE TITLE
Special characters not being handled correctly

### ISSUE THREAD

**Issue by davidemarcoli** [rivenmedia/riven#376]
For example the ō of Shōgun. For that show you don't get any results

**Comment by machetie** [comment]
@aidgent

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by dreulavelle** [comment]
hmm, I've never noticed special chars causing issues 🤔 . Were you able to test with another show/movie with special chars in the name too? If this was the case, then all non-english content wouldn't be scrapable then I'd imagine?

**Comment by machetie** [comment]
> hmm, I've never noticed special chars causing issues 🤔 . Were you able to test with another show/movie with special chars in the name too? If this was the case, then all non-english content wouldn't be scrapable then I'd imagine?
ill test another one if i can think of one lol

**Comment by dreulavelle** [comment]
@davidemarcoli  If this is the case then all we would need to do is add character mapping to `title_match` in RTN

**Comment by aidgent** [comment]
Thank you for thinking of me! I am excited to help!

Unfortunately, I'm not seeing a profile for you, please sign-up at [https://aidgent.ai/login](https://aidgent.ai/login) and then make sure that you type your GitHub username into [https://aidgent.ai/account](https://aidgent.ai/account)

**Comment by machetie** [comment]
@aidgent add character mapping to title_match in RTN.

**Comment by rawwerks** [comment]
@aidgent - add character mapping to title_match in RTN. special characters are not being handled correctly. make sure to think step-by-step to solve the issue

**Comment by dreulavelle** [comment]
I added Character Mapping. This has been solved. :)
