### ISSUE TITLE
Check for service status once configured in onboarding

### ISSUE THREAD

**Issue by AyushSehrawat** [rivenmedia/riven#384]
In the frontend rewrite, onboarding will only look for symlink and symlinklibrary service. If those fail, user will be popped up with onboarding again. But frontend onboarding also needs to check  for service status for each settings configuration like overseerr, mdblist, jackett etc. Currently it doesn't work well because there is no group service except `scraping`. We either need to make more similar group service like `content` and `downloader` or some other way in frontend

**Comment by davidemarcoli** [comment]
Aren't we already grouping all of them?

**Comment by AyushSehrawat** [comment]
There's only scraper service which is grouped from what i see in services endpoint
