### ISSUE TITLE
Special characters not being handled correctly

### ISSUE THREAD

**Issue by rawwerks** [rivenmedia/riven#386]
@aidgent - special characters are not being handled correctly. 

For example the ō of Shōgun. For that show you don't get any results

If this is the case then all we would need to do is add character mapping to title_match in RTN

add character mapping to title_match in RTN.

add character mapping to title_match in RTN. special characters are not being handled correctly. make sure to think step-by-step to solve the issue

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by dreulavelle** [comment]
```py
def translate_name(name: str) -> str:
    toChange = {
        'ā': 'a', 'ă': 'a', 'ą': 'a', 'ć': 'c', 'č': 'c', 'ç': 'c',
        'ĉ': 'c', 'ċ': 'c', 'ď': 'd', 'đ': 'd', 'è': 'e', 'é': 'e',
        'ê': 'e', 'ë': 'e', 'ē': 'e', 'ĕ': 'e', 'ę': 'e', 'ě': 'e',
        'ĝ': 'g', 'ğ': 'g', 'ġ': 'g', 'ģ': 'g', 'ĥ': 'h', 'î': 'i',
        'ï': 'i', 'ì': 'i', 'í': 'i', 'ī': 'i', 'ĩ': 'i', 'ĭ': 'i',
        'ı': 'i', 'ĵ': 'j', 'ķ': 'k', 'ĺ': 'l', 'ļ': 'l', 'ł': 'l',
        'ń': 'n', 'ň': 'n', 'ñ': 'n', 'ņ': 'n', 'ŉ': 'n', 'ó': 'o',
        'ô': 'o', 'õ': 'o', 'ö': 'o', 'ø': 'o', 'ō': 'o', 'ő': 'o',
        'œ': 'oe', 'ŕ': 'r', 'ř': 'r', 'ŗ': 'r', 'š': 's', 'ş': 's',
        'ś': 's', 'ș': 's', 'ß': 'ss', 'ť': 't', 'ţ': 't', 'ū': 'u',
        'ŭ': 'u', 'ũ': 'u', 'û': 'u', 'ü': 'u', 'ù': 'u', 'ú': 'u',
        'ų': 'u', 'ű': 'u', 'ŵ': 'w', 'ý': 'y', 'ÿ': 'y', 'ŷ': 'y',
        'ž': 'z', 'ż': 'z', 'ź': 'z', 'æ': 'ae', 'ǎ': 'a', 'ǧ': 'g',
        'ə': 'e', 'ƒ': 'f', 'ǐ': 'i', 'ǒ': 'o', 'ǔ': 'u', 'ǚ': 'u',
        'ǜ': 'u', 'ǹ': 'n', 'ǻ': 'a', 'ǽ': 'ae', 'ǿ': 'o',
    }
    translationTable = str.maketrans(toChange)
    return name.translate(translationTable)
    ```
    
    I just need to add it but I've been too busy

**Comment by rawwerks** [comment]
thanks! sorry to spam your repo, i was just trying to see if i could help @machiete get unstuck with aidgent, but for some reason aidgent is timing out when trying to work on this repo.

**Comment by dreulavelle** [comment]
maybe too much commit history or modules inside? No worries though! Just a heads up though that this is already on my radar. :)

**Comment by aidgent** [comment]
Thank you for thinking of me! I am excited to help!

Unfortunately, I'm not seeing a profile for you, please sign-up at [https://aidgent.ai/login](https://aidgent.ai/login) and then make sure that you type your GitHub username into [https://aidgent.ai/account](https://aidgent.ai/account)
