### ISSUE TITLE
Torbox and Debrid Integration

### ISSUE THREAD

**Issue by FiveMDevv** [rivenmedia/riven#392]
- UnionFS Example
- Allow an option in the scraping catagory to chose what provider you want to send to RD or Torbox
  - Will be useful if using private trackers

**Comment by dreulavelle** [comment]
UnionFS is outside the scope really.. each service was meant to be used independently.. however I think a UnionFS might be possible.. this will require testing from users.. not something thats of high importance to us right now.

If you can get it working and document it for us, we can add it! Torbox needs testing as its not implemented 100% currently. It's a big WIP right now.

**Comment by FiveMDevv** [comment]
Sounds good. Maybe having a seperate rclone path for torbox could work!

**Comment by DrMxrcy** [comment]
I agree 

- Having a separate rclone path would help with some of the slow torbox issues I have seen.

- Would be nice to be able to tag certain search providers to go to torbox or debrid. Example would be configure Usenet and Private Trackers in prowlarr and send them all to torbox.
