### ISSUE TITLE
[Question] Will it feature alldebrid ?

### ISSUE THREAD

**Issue by C0gn1to** [rivenmedia/riven#411]
Hi, I just discovered this really cool projet and I have 2 questions:

1. As its a plex_debrid rewrite, will it feature alldebrid as debrid service ? Because from what I see it seems to only support RD
2. I tried to run it on my serveur but I noticed it doesn't have web interface for now, do you know approximately when it will have one ?

Thank you for your hard work, peace

**Comment by dreulavelle** [comment]
If alldebrid offers webdav, then yes we can eventually get to it. If not, then we never would be able to support it

**Comment by Crackvignoule** [comment]
> If alldebrid offers webdav, then yes we can eventually get to it. If not, then we never would be able to support it

Of course it provides webdav. https://help.alldebrid.com/en/Alldebrid%20tools/webdav
Thanks

**Comment by dreulavelle** [comment]
I havent used the other debrids except Real Debrid because its been the best and cheapest option, and most popular.

**Comment by C0gn1to** [comment]
> I havent used the other debrids except Real Debrid because its been the best and cheapest option, and most popular.

Alldebrid is 2.99$ a month and personnaly I prefer it, it also has a ton of content in cache like RD. I would just love to use Riven the same way Im using plex_debrid but with a more convenaient UI.

**Comment by dreulavelle** [comment]
With it's webdav, does it offer unlimited storage as well like RD?

I do already plan on supporting other Debrid services. Would be nice to support them all.

**Comment by C0gn1to** [comment]
> With it's webdav, does it offer unlimited storage as well like RD?
> 
> I do already plan on supporting other Debrid services. Would be nice to support them all.

Yes if course unlimited storage, At least I think because I have many TB and I've not seen any mention of limitation
