### ISSUE TITLE
Compose error

### ISSUE THREAD

**Issue by drizzt09** [rivenmedia/riven#412]
installed compose and gets all the way to the end and there is this line:
[SUCCESS] [OPERATION SUCCEEDED]. SERVICE STARTED
{"status":"error","message":"Gateway Timeout","code":"HTTP002"}

docker shows running:
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                       NAMES
162f8973bfb1   spoked/iceberg:latest          "fish /iceberg/entry…"   7 minutes ago    Up 6 minutes    0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   iceberg

        "ORIGIN=https://***********.duckdns.org:3000",

but unable to get to URL
https://*********.duckdns.org:3000

Hmmm… can't reach this page
*********.duckdns.org refused to connect.

Self hosted on Ubuntu 20.04

**Comment by dreulavelle** [comment]
whats the compose look like

**Comment by drizzt09** [comment]
I copied the compose from the instructions and only edited the origin which
I already provided.

**Comment by dreulavelle** [comment]
the readme one is probably wrong, it hasnt been updated in forever. I'd recommend the `docker-compose.yml` file in the repo

**Comment by drizzt09** [comment]
ok deleted container and rebuilt using the yml.
this time I got:
[SUCCESS] [OPERATION SUCCEEDED]. SERVICE STARTED

but not this one this time:
{"status":"error","message":"Gateway Timeout","code":"HTTP002"}

but still get:
xxxxxxxxx.duckdns.org refused to connect.

Even though it is running:
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                       NAMES
2b8a5c08c167   spoked/iceberg:latest          "fish /iceberg/entry…"   7 minutes ago   Up 7 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   iceberg

**Comment by AyushSehrawat** [comment]
Try the latest image @drizzt09 from scratch

This feels like your side issue most probably

**Comment by drizzt09** [comment]
What do you mean by try latest image? I already grabbed the latest compose
and started from scratch. Same problem.

Yes I know it's an issue on my end, as I seem to be the only one that has
reported it. Hence the reason I am here for help on finding what is the
problem.

**Comment by dreulavelle** [comment]
I just now updated the readme, the compose, the CI pipeline, as well as added some env var examples as well.

There shouldn't be a reason that you wouldn't be able to connect to the container as we expose the `3000` port thats needed for the frontend.

Also, the frontend doesn't work currently anyways as its undergoing a rewrite.

**Comment by drizzt09** [comment]
Even though it's on on 1 pc local in my environment. Could it be because
I'm using https with an external duckdns domain? So it's going out and
coming back in and I need 3000 exposed in the router?

**Comment by dreulavelle** [comment]
DNS resolving is a bit outside the scope of what we do here. 

That being said, why not just use localhost? We dont have SSL certificates inside the container so any SSL would have to be handled by you. Chances are it would be http instead of https. You don't need to expose ports on the router for a local app

**Comment by drizzt09** [comment]
i have rebuilt using http://localhost:3000, http://dnsname.duckdns.org:3000, http://hostname:3000, and http://hostname.local:3000.

all get same issue. note i am on 1 PC, running on another PC. so localhost wont actually work on a remote PC.
both PC are within the same home network. 192.168.0.xxx
