### ISSUE TITLE
Overseerr webhook issue

### ISSUE THREAD

**Issue by eoghan2t9** [rivenmedia/riven#471]
Can someone possibly give me any ideas as to why my webhook won't start I'm on the latest riven version and this is all the logs say even though both riven and overseerr have been running for a few days?

overseerr.run - Webhook is enabled, but running Overseerr once before switching to webhook

Any ideas in getting it enabled fully would be great 😃

**Comment by dreulavelle** [comment]
Whats your Overseerr settings look like? Whats the webhook url you setup in Overseerr?

**Comment by eoghan2t9** [comment]
These are the settings I have set:

![Screenshot_20240627-061543.png](https://github.com/rivenmedia/riven/assets/911750/7c7a2778-c176-4db5-85f0-0dfb6b1d588c)

![Screenshot_20240627-061517.png](https://github.com/rivenmedia/riven/assets/911750/1888248d-6719-4a34-b3d9-96f44c37e7cd)

**Comment by dreulavelle** [comment]
![image](https://github.com/rivenmedia/riven/assets/5782630/d98da4fc-f023-446b-b71a-df70f3e91a87)
this is the issue.

`ip:8080/webhook/overseerr`

**Comment by eoghan2t9** [comment]
Oh I'm running it locally so would my port not be 3000 that's set in the compose file?

**Comment by dreulavelle** [comment]
3000 is the frontend port, 8080 is the backend api. The webhook is on the backend api, so it needs port 8080

**Comment by Gaisberg** [comment]
We could expose it via frontend?

**Comment by dreulavelle** [comment]
yeah but then that means Mini has to do it.. and that'll be a while 😅

**Comment by eoghan2t9** [comment]
You absolute legend that's me running now ;)

**Comment by dreulavelle** [comment]
Awesome man! :)
