### ISSUE TITLE
Question: How to download music files without RD rar them

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [rivenmedia/riven#472]
Hi, I use something similar to your project and since I want to use Jellyfin instead of plex. I can't really use this project (but great work nonetheless) I use *arr with Zurg and RDT Client. all using docker compose.

My question is one I know uses your project and seems to be able to download music fine but whenever I try so RD rar the content (because it's not movie file type) and RDT client get stuck as it can't unrar a symlink...so how Riven actually work to overcome this issue and not let RD rar files or unrar the files but in same time download files as symlinks only.

Thanks in advance!

**Comment by AyushSehrawat** [comment]
> Hi, I use something similar to your project and since I want to use Jellyfin instead of plex. I can't really use this project (but great work nonetheless) I use *arr with Zurg and RDT Client. all using docker compose.

Jellyfin csn

**Comment by AyushSehrawat** [comment]
> Hi, I use something similar to your project and since I want to use Jellyfin instead of plex. I can't really use this project (but great work nonetheless) I use *arr with Zurg and RDT Client. all using docker compose.

Jellyfin works, but you need to use autoscan / manually scan, expect full Jellyfin support in future.

Regarding rar, i think we ignore rars,, @dreulavelle might know more

**Comment by EsmailELBoBDev2** [comment]
good to know and about rars so t do not unrar rared files from RD correct?

**Comment by dreulavelle** [comment]
Riven doesn't support music

**Comment by EsmailELBoBDev2** [comment]
> Riven doesn't support music

oh well, thanks answering.

**Comment by dreulavelle** [comment]
I believe DMM/Zurg just added music support. So you may have to try that route. Otherwise check out Lidarr at https://lidarr.audio/

**Comment by EsmailELBoBDev2** [comment]
I do have lidarr, my issue is RD that rar mp3 and flac so when I use RDT Client to download (symlink downloader) it can't unrar that.

Do I miss something?

**Comment by dreulavelle** [comment]
Thats a RDT issue.. but Zurg should be unraring them

**Comment by EsmailELBoBDev2** [comment]
> Thats a RDT issue.. but Zurg should be unraring them

even if they are symlinks?

**Comment by dreulavelle** [comment]
if they are symlinks then they've already been unrar'ed and you shouldnt have issues. But Riven doesnt select music files in RD nor does it scrape for music.. so for those reasons, we dont support Music :P

**Comment by EsmailELBoBDev2** [comment]
got it but in RD case..it gets download link after rar(ed) from RD so it cant unrar symlinks. thats what I do not understand and need someone to clarify it to me

**Comment by Pukabyte** [comment]
Maybe head over to Zurgs GitHub and ask there, as this is not a Riven related issue, or jump in the discord :)

**Comment by EsmailELBoBDev2** [comment]
> Maybe head over to Zurgs GitHub and ask there, as this is not a Riven related issue, or jump in the discord :)

yup just did that and asked there, thanks for all of you for help tho! Have a nice day
