### ISSUE TITLE
Trakt Item creation can have wrong year for movies

### ISSUE THREAD

**Issue by dreulavelle** [rivenmedia/riven#477]
I noticed for 1 movie that it created a Movie item with the wrong year. Trakt and Overseerr had the correct year, but it got created with the wrong year.. maybe `datetime` lib is wrong?

Need to look into this one.

**Comment by AyushSehrawat** [comment]
> I noticed for 1 movie that it created a Movie item with the wrong year. Trakt and Overseerr had the correct year, but it got created with the wrong year.. maybe `datetime` lib is wrong?
> 
> Need to look into this one.

datetime lib is the best it can get, and even if there was +-24Hr difference, it would still be the same year. What's the date returned by trakt api for it ?

**Comment by dreulavelle** [comment]
Trakt and Overseerr had the correct year, 1964 (Mary Poppins) but the item got created with year 1965 🤨

**Comment by AyushSehrawat** [comment]
> Trakt and Overseerr had the correct year, 1964 (Mary Poppins) but the item got created with year 1965 🤨

Weird, is it some weird unix timestamp bug ?

**Comment by dreulavelle** [comment]
Solved.
