### ISSUE TITLE
mediaserver Page in settings is throwing an error code 500

### ISSUE THREAD

**Issue by YaarPatandarAA** [rivenmedia/riven#485]
Like stated in the title when navigating to /settings/mediaserver it is showing a Something went wrong message and saying Error Code 500.

This is inside of a Docker Container I am running Riven. It's the latest version and a fresh install, haven't even configured anything. I was hoping to configure in the settings but that isn't working.

What am I missing?

**Comment by dreulavelle** [comment]
this is normal. last update broke the page. but the whole frontend is being worked on anyways, so just use the settings.json file to edit your settings

**Comment by YaarPatandarAA** [comment]
oh, well that was a lost of wasted hours. 
Thanks for the quick update
