### ISSUE TITLE
Core Services Plex Library

### ISSUE THREAD

**Issue by MVethana** [rivenmedia/riven#500]
Plex library is showing as red, unable to link it manually since the media server tab is broken. I've configured the plex URL and token in settings.json. Not seeing anything in the logs either.

![image](https://github.com/rivenmedia/riven/assets/17278251/658ab4a1-0f94-4669-a807-f19324fd83fb)

**Comment by AyushSehrawat** [comment]
Plex Library has been removed from the services, not yet updated in frontend. Frontend is coming with some improvements soon.

#422 is the initial new ui interface
