### ISSUE TITLE
raise RuntimeError('cannot schedule new futures after shutdown')

### ISSUE THREAD

**Issue by MVethana** [rivenmedia/riven#501]
Riven starts, all pages work for a while, then after a bit, the front end pages refuse to load load, returning internal error 500 with the following log error

Jul  9, 2024 23:53:33 - INFO - Riven_frontend: TypeError: fetch failed
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: at node:internal/deps/undici/undici:12500:13
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: [cause]: Error: connect ECONNREFUSED 127.0.0.1:8080
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: errno: -111,
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: code: 'ECONNREFUSED',
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: syscall: 'connect',
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: address: '127.0.0.1',
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: port: 8080
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: }
Jul  9, 2024 23:53:33 - INFO - Riven_frontend: }
Jul  9, 2024 23:53:35 - INFO - Riven_backend: Error submitting job "Program._submit_job (trigger: interval[0:01:00], next run at: 2024-07-09 23:53:35 UTC)" to executor "default"
Jul  9, 2024 23:53:35 - INFO - Riven_backend: Traceback (most recent call last):
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
Jul  9, 2024 23:53:35 - INFO - Riven_backend: executor.submit_job(job, run_times)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
Jul  9, 2024 23:53:35 - INFO - Riven_backend: self._do_submit_job(job, run_times)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
Jul  9, 2024 23:53:35 - INFO - Riven_backend: f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
Jul  9, 2024 23:53:35 - INFO - Riven_backend: raise RuntimeError('cannot schedule new futures after shutdown')
Jul  9, 2024 23:53:35 - INFO - Riven_backend: RuntimeError: cannot schedule new futures after shutdown
Jul  9, 2024 23:53:35 - INFO - Riven_backend: Error submitting job "Program._submit_job (trigger: interval[0:01:00], next run at: 2024-07-09 23:53:35 UTC)" to executor "default"
Jul  9, 2024 23:53:35 - INFO - Riven_backend: Traceback (most recent call last):
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
Jul  9, 2024 23:53:35 - INFO - Riven_backend: executor.submit_job(job, run_times)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
Jul  9, 2024 23:53:35 - INFO - Riven_backend: self._do_submit_job(job, run_times)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/venv/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
Jul  9, 2024 23:53:35 - INFO - Riven_backend: f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
Jul  9, 2024 23:53:35 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul  9, 2024 23:53:35 - INFO - Riven_backend: File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
Jul  9, 2024 23:53:35 - INFO - Riven_backend: raise RuntimeError('cannot schedule new futures after shutdown')
Jul  9, 2024 23:53:35 - INFO - Riven_backend: RuntimeError: cannot schedule new futures after shutdown

**Comment by AyushSehrawat** [comment]
Backend fails due to the above error, causes API to not start, hence the error.

Does restarting fixed it? Try deleting media.pkl and media.pkl.bak and restart

@dreulavelle look into it 👍🏻.

**Comment by MVethana** [comment]
Happens consistently after restart within a couple min, will delete and report back

**Comment by AyushSehrawat** [comment]
> Happens consistently after restart within a couple min, will delete and report back

Ehicj

**Comment by AyushSehrawat** [comment]
> Happens consistently after restart within a couple min, will delete and report back

Which content service you use? Overseer or some other? Lookout if any item is without poster in thenm

**Comment by MVethana** [comment]
I originally linked my existing overseerr that had been used for a while so all the old requests got sent to Riven. Having trouble locating the file you mentioned, currently using aio DMB if that helps

**Comment by AyushSehrawat** [comment]
> I originally linked my existing overseerr that had been used for a while so all the old requests got sent to Riven. Having trouble locating the file you mentioned, currently using aio DMB if that helps

Can you check in overseerr's request page if some item is missing posters?

**Comment by MVethana** [comment]
I have over 2k requests in there, did find this one as an example
![image](https://github.com/rivenmedia/riven/assets/17278251/ff69d3ef-4db8-4de4-a09c-0f0d86375cab)

**Comment by AyushSehrawat** [comment]
> I have over 2k requests in there, did find this one as an example ![image](https://private-user-images.githubusercontent.com/17278251/347247883-ff69d3ef-4db8-4de4-a09c-0f0d86375cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODMwMzYsIm5iZiI6MTcyMDU4MjczNiwicGF0aCI6Ii8xNzI3ODI1MS8zNDcyNDc4ODMtZmY2OWQzZWYtNGRiOC00ZGU0LWEwOWMtMGYwZDg2Mzc1Y2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMWFmZTk4NzRkZGRkZGQ4Yzk1M2ZlNzhkMzNhNjE2MDY4MWJiZjg0YTY5YjkzYjlkOTA5Zjk5NzQzOGUxMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wF9md2GGoSMivrMc8z13r4BdID-qozfr1sRS_T9zAVw)

Remove it and then either delete media.pkl and media.pkl.bak or remove from api

**Comment by AyushSehrawat** [comment]
@MVethana keep it open, we need to be handle such instances

@dreulavelle ^^

**Comment by dreulavelle** [comment]
this isnt the error.. its above these logs. these logs show that it cant schedule new jobs since it was closed down.. the real error is above this... 

@MVethana We need to see the rest of the logs **above** these errors

**Comment by AyushSehrawat** [comment]
> this isnt the error.. its above these logs. these logs show that it cant schedule new jobs since it was closed down.. the real error is above this...
> 
> @MVethana We need to see the rest of the logs **above** these errors

I think it's related to bad item in overseerr, changed ids or removed etc

**Comment by dreulavelle** [comment]
it could also be a Movie error that uses the wrong attribute that doesnt exist.. I've seen that one too. It can be anything.. these logs don't show the error

**Comment by MVethana** [comment]
I can repro by adding my existing overseerr library again, will do

**Comment by MVethana** [comment]
Jul 11, 2024 14:29:47 - ERROR - Riven_backend: | main.<module> - Error in main thread: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:47 - INFO - Riven_backend: | 🤖 PROGRAM   | program._remove_from_running_items - #########
Jul 11, 2024 14:29:47 - INFO - Riven_backend: | 🔍 DISCOVERY | program._push_event_queue - #########
Jul 11, 2024 14:29:47 - INFO - Riven_backend: | 📽️  LOCAL     | local.run - Updated Switch
Jul 11, 2024 14:29:47 - ERROR - Riven_backend: | main.<module> - Traceback (most recent call last):
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/main.py", line 114, in <module>
Jul 11, 2024 14:29:47 - INFO - Riven_backend: app.program.run()
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 372, in run
Jul 11, 2024 14:29:47 - INFO - Riven_backend: self.add_to_running(event.item, "program.run")
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 264, in add_to_running
Jul 11, 2024 14:29:47 - INFO - Riven_backend: logger.log("PROGRAM", f"Item {item.log_string} started running section {service_name}" )
Jul 11, 2024 14:29:47 - INFO - Riven_backend: ^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:47 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:47 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:47 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:47 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/main.py", line 114, in <module>
Jul 11, 2024 14:29:47 - INFO - Riven_backend: app.program.run()
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 372, in run
Jul 11, 2024 14:29:47 - INFO - Riven_backend: self.add_to_running(event.item, "program.run")
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 264, in add_to_running
Jul 11, 2024 14:29:47 - INFO - Riven_backend: logger.log("PROGRAM", f"Item {item.log_string} started running section {service_name}" )
Jul 11, 2024 14:29:47 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:47 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:47 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'

Jul 11, 2024 14:29:46 - ERROR - Riven_backend: | program._process_future_item - Service TraktIndexer failed with exception Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:46 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:46 - INFO - Riven_backend: | 🤖 PROGRAM   | program._remove_from_running_items - Item tt21316834 finished running section TraktIndexer
Jul 11, 2024 14:29:46 - ERROR - Riven_backend: | program._process_future_item - Service TraktIndexer failed with exception Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:46 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:46 - INFO - Riven_backend: | 🤖 PROGRAM   | program._remove_from_running_items - Item tt13820496 finished running section TraktIndexer
Jul 11, 2024 14:29:46 - ERROR - Riven_backend: | program._process_future_item - Service TraktIndexer failed with exception Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:46 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:46 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:46 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:46 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:46 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:46 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'


Jul 11, 2024 14:29:45 - ERROR - Riven_backend: | program._process_future_item - Service TraktIndexer failed with exception Traceback (most recent call last):
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:45 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:45 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:45 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:45 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:45 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:45 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:45 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:45 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:45 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:45 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:45 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:45 - INFO - Riven_backend: | 🤖 PROGRAM   | program._remove_from_running_items - Item tt21316870 finished running section TraktIndexer
Jul 11, 2024 14:29:45 - ERROR - Riven_backend: | program._process_future_item - Service TraktIndexer failed with exception Traceback (most recent call last):
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:45 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:45 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:45 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:45 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:45 - INFO - Riven_backend: ^^^^^^^^^^^^^^^^^^^^^^
Jul 11, 2024 14:29:45 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'
Jul 11, 2024 14:29:45 - INFO - Riven_backend: Traceback (most recent call last):
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 291, in _process_future_item
Jul 11, 2024 14:29:45 - INFO - Riven_backend: self._push_event_queue(Event(emitted_by=service, item=item))
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/program.py", line 246, in _push_event_queue
Jul 11, 2024 14:29:45 - INFO - Riven_backend: logger.log("DISCOVERY", f"Re-added {event.item.log_string} to the queue" )
Jul 11, 2024 14:29:45 - INFO - Riven_backend: File "/riven/backend/program/media/item.py", line 438, in log_string
Jul 11, 2024 14:29:45 - INFO - Riven_backend: return f"{self.parent.log_string}E{self.number:02}"
Jul 11, 2024 14:29:45 - INFO - Riven_backend: AttributeError: 'NoneType' object has no attribute 'log_string'

**Comment by dreulavelle** [comment]
which branch is this?

**Comment by MVethana** [comment]
main, running through aio DMB

**Comment by dreulavelle** [comment]
aio DMB?

**Comment by MVethana** [comment]
All In One - Debrid Media Bridge
https://github.com/I-am-PUID-0/DMB
All it does is combine riven and the other apps together, riven itself is the one giving the error here

**Comment by dreulavelle** [comment]
I'm wondering if his is out of date or something. You're getting a lot of the `NoneType` errors. More so than you should be getting. It is a known bug, but I havent seen it pop up as many times as I'm seeing from your logs.

Are you working with a list, or did you just request a few items?

Right now, Documentaries, Mini-Series, Soaps and some old classic shows/movies don't work that great. It's coming up with NoneType because it wasn't able to index the item with an IMDb ID.  Our indexing is going to get reworked to improve this as well. I'm hoping to put it in with the `0.8.0` release though.

**Comment by MVethana** [comment]
It pulls the latest straight from main, to repro the errors I reattached my existing overseer with 2k+ requests. It automatically added all my existing items into Riven.

![image](https://github.com/user-attachments/assets/42a223d2-d3a5-49af-9538-a7adaa58c31d)
