### ISSUE TITLE
Can't progress with onboarding

### ISSUE THREAD

**Issue by tbgoose** [rivenmedia/riven#524]
Hi all

Have installed Riven / Overseerr / Plex on my OCI for a bit of a play. Running Cosmos-Server as the OS.

I can't progress with onboarding as nothing happens when I click the _Save changes and continue_ button. My logs show I haven't set things up correctly (like symlinks), however I can't fix those problems as can't do onboarding... Any tips?

Any tips to how to proceed?

**Comment by dreulavelle** [comment]
Sounds like you didn't set the origin environment variable correctly. You need to set it to the ip that you use it from. Or the FQDN that you use to access the frontend. That will fix it for you

**Comment by tbgoose** [comment]
Great thanks that fixed it, changed from cloud instance IP to FQDN provided by OCI.
