### ISSUE TITLE
Items with lower rank selected over better items

### ISSUE THREAD

**Issue by deepvalu** [rivenmedia/riven#537]
Despite being last on the list, I see many lower ranked items being selected. 

24-07-17 13:29:53 | 👻 SCRAPER   | shared._parse_results - Processed 3 matches for Bad Sisters
24-07-17 13:29:53 | 🤖 DEBUG     | __init__.scrape - [Show] Parsed 'Bad Sisters' with rank 5215 and ratio 1.00: 'Bad Sisters S01 1080p WEBRip x265'
24-07-17 13:29:53 | 🤖 DEBUG     | __init__.scrape - [Show] Parsed 'Bad Sisters' with rank 5215 and ratio 1.00: 'Bad.Sisters.S01.1080p.WEBRip.x265-RARBG'
24-07-17 13:29:53 | 🤖 DEBUG     | __init__.scrape - [Show] Parsed 'Bad Sisters' with rank 205 and ratio 1.00: 'Bad.Sisters.S01.COMPLETE.720p.ATVP.WEBRip.x264-GalaxyTV'`` 

 24-07-17 13:54:04 | 🤖 DEBUG     | realdebrid._download_item - Item marked as downloaded: Bad Sisters
24-07-17 13:54:04 | 🔗 DEBRID    | realdebrid.log_item - Downloaded Bad Sisters S01E01 with file: Bad.Sisters.S01E01.720p.ATVP.WEBRip.x264-GalaxyTV.mkv
24-07-17 13:54:04 | 🔗 DEBRID    | realdebrid.log_item - Downloaded Bad Sisters S01E02 with file: Bad.Sisters.S01E02.720p.ATVP.WEBRip.x264-GalaxyTV.mkv
24-07-17 13:54:04 | 🔗 DEBRID    | realdebrid.log_item - Downloaded Bad Sisters S01E03 with file: Bad.Sisters.S01E03.720p.ATVP.WEBRip.x264-GalaxyTV.mkv
24-07-17 13:54:04 | 🔗 DEBRID    | realdebrid.log_item - Downloaded Bad Sisters S01E04 with file: Bad.Sisters.S01E04.720p.ATVP.WEBRip.x264-GalaxyTV.mkv
24-07-17 13:54:04 | 🤖 PROGRAM   | program._remove_from_running_items - Item Bad Sisters finished running section Debrid

**Comment by dreulavelle** [comment]
I can look into this, but it is worth noting that just because we scraped something, doesnt mean that its cached or that it has all the episodes we need. Just something to keep in mind.
