### ISSUE TITLE
[Bug] [Backend] Wrong anime categorization

### ISSUE THREAD

**Issue by rybertm** [rivenmedia/riven#539]
## Expected Behavior
Anime shows and movies being correctly categorized as such

## Actual Behavior
Being wrongly categorized

## Steps to Reproduce the Problem

  1. Create separate libraries for Anime Shows/Anime Movies/Shows/Movies
  2. Make a request (I used overseerr) to a anime show
  3. Check where the show was imported to

## Specifications

  - Version: [0355e64](https://github.com/rivenmedia/riven/commit/0355e6485c6e43f66a04165a85a890aaf1d8c0c3)
  - Platform: Ubuntu 22.04 (x64 and aarch64)
  - Summary (only available/green):
      * Core Services: 
          - `Symlink Library`
          - `Symlink`
          - `Scraping`
          - `Updater`
      * Downloader services:
          - `Real Debrid`
      * Content services: 
          - `Overseerr`
      * Scraping services: 
          - `Torrentio`

**Comment by dreulavelle** [comment]
This is a known bug, movies should work fine but Show items arent working very well.. Indexing is looking to be rewritten though soon which will fix this :)

**Comment by rybertm** [comment]
Didn't find a mention when searching the issues.

I have a small PR which fixes this (literally one liner), should I still create it?

**Comment by dreulavelle** [comment]
yeah, create it and I can test it :)

**Comment by AyushSehrawat** [comment]
Close as fixed ?

**Comment by rybertm** [comment]
Fixed in c7c07a50c1
