### ISSUE TITLE
[Bug] Incomplete scraping of anime shows

### ISSUE THREAD

**Issue by rybertm** [rivenmedia/riven#545]
## Expected Behavior
Anime shows with multiple seasons get scraped/downloaded normally

## Actual Behavior
The show only scrapes 1 season

## Steps to Reproduce the Problem

  1. Request an anime show with multiple seasons but that says it only has 1 season with multiple episodes (Overseer and Trakt does this e.g [Jujutsu Kaisen](https://trakt.tv/shows/jujutsu-kaisen#seasons))

## Specifications

  - Version: Any version
  - Platform: Ubuntu 22.04 (x64 and aarch64)
  - Summary (only available/green):
      * Core Services: 
          - `Symlink Library`
          - `Symlink`
          - `Scraping`
          - `Updater`
      * Downloader services:
          - `Real Debrid`
      * Content services: 
          - `Overseerr`
      * Scraping services: 
          - `Torrentio`

## Thoughts

Since this is a problem at its core with the content providers and indexers (Overseerr, Trakt at least) we should do some more bookeeping with anime shows to correctly separate them.

Haven't looked but my assumption is that we are too strict when scraping given the initial media requested (as we should) but that means we end up not getting seasons when the provider/indexer categorizes an anime with multiple seasons as a 1 season only.

I plan to look into it. Should I just go with softening the rules when scraping of anime shows to make sure we get them all or should I look into using a more accurate indexer for anime?

**Comment by dreulavelle** [comment]
Indexing in general needs improvement for sure. I'm wondering if we index anime separately from a different API. Have suggestions on good api's for that task?

**Comment by AyushSehrawat** [comment]
> Indexing in general needs improvement for sure. I'm wondering if we index anime separately from a different API. Have suggestions on good api's for that task?

Trakt should be good, or maybe tmdb if you wanna switch

But if you want to do look into MAL or Anilist, anilist has better api and docs https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting

**Comment by AyushSehrawat** [comment]
> Haven't looked but my assumption is that we are too strict when scraping given the initial media requested (as we should) but that means we end up not getting seasons when the provider/indexer categorizes an anime with multiple seasons as a 1 season only.
> I plan to look into it. Should I just go with softening the rules when scraping of anime shows to make sure we get them all or should I look into using a more accurate indexer for anime?

I think that's the issue with anime torrents only. Like One Piece, it's actually 10s of season but torrents are usually E1034 instead of S23E43 (example)

**Comment by rybertm** [comment]
> But if you want to do look into MAL or Anilist, anilist has better api and docs https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting

I'll look into it when I have time

> I think that's the issue with anime torrents only. Like One Piece, it's actually 10s of season but torrents are usually E1034 instead of S23E43 (example)

Used [Jujutsu Kaisen](https://trakt.tv/shows/jujutsu-kaisen#seasons) as an example. Both Trakt and Overseer list both seasons as only 1.

**Comment by rybertm** [comment]
I found https://github.com/Fribb/anime-lists where it has mappings between anime ids and different sources. 

But from the ones I looked their api was either lacking (having only number of episodes, no season information, or it would have them separated as different shows or straight up paid).

Need further investigating here.
