### ISSUE TITLE
[Bug] state changes not being persisted when season/episode causes the show to change state

### ISSUE THREAD

**Issue by rybertm** [rivenmedia/riven#548]
## Expected Behavior
The state change should be persisted to the db

## Actual Behavior
Only the children's state are persisted

## Steps to Reproduce the Problem

  1. Request [House M.D.](https://trakt.tv/shows/house)
  2. Wait for it to finish the whole show
  3. Check each Episode for S07. It will correctly be `Completed`
  4. Check Season 7 `last_state` in the db. It will be `Indexed` when it should be `Completed`
  5. Check Show `last_state` in the db. It will be `Scraped` when it should be `Completed`

## Specifications

  - Version: Any version from [release_080](https://github.com/rivenmedia/riven/tree/release_080) branch
  - Platform: Ubuntu 22.04 (x64 and aarch64)
  - Summary (only available/green):
      * Core Services: 
          - `Symlink Library`
          - `Symlink`
          - `Scraping`
          - `Updater`
      * Downloader services:
          - `Real Debrid`
      * Content services: 
          - `Overseerr`
      * Scraping services: 
          - `Torrentio`

**Comment by rybertm** [comment]
Plan to look into it

**Comment by Gaisberg** [comment]
Is this still an issue?
