### ISSUE TITLE
TraktIndexer never progresses past submitting job

### ISSUE THREAD

**Issue by deepvalu** [rivenmedia/riven#566]
Using trakt for content, it never actually scrapes for content. It just endlessly loops. 

`24-07-23 13:49:38 | 🤖 PROGRAM   | program._remove_from_running_items - Item Boiling Point finished running section program.run

24-07-23 13:49:38 | 🤖 PROGRAM   | program.add_to_running - Item tt11127680 started running section TraktIndexer

24-07-23 13:49:38 | ✨ NEW       | program._submit_job - Submitting service TraktIndexer to the pool with tt11127680

24-07-23 13:49:38 | 🤖 PROGRAM   | program._remove_from_running_items - Item tt17009710 finished running section TraktIndexer

24-07-23 13:49:38 | 🔍 DISCOVERY | program._push_event_queue - Re-added Anatomy of a Fall to the queue

24-07-23 13:49:38 | 🤖 PROGRAM   | program._process_future_item - Service TraktIndexer finished running on tt17009710

24-07-23 13:49:38 | 🤖 PROGRAM   | program.add_to_running - Item Anatomy of a Fall started running section program.run

24-07-23 13:49:38 | 🤖 PROGRAM   | program._remove_from_running_items - Item Anatomy of a Fall finished running section program.run

24-07-23 13:49:38 | 🤖 PROGRAM   | program.add_to_running - Item tt17009710 started running section TraktIndexer

24-07-23 13:49:38 | ✨ NEW       | program._submit_job - Submitting service TraktIndexer to the pool with tt17009710

24-07-23 13:49:38 | 🤖 PROGRAM   | program._remove_from_running_items - Item tt1856080 finished running section TraktIndexer

24-07-23 13:49:38 | 🤖 PROGRAM   | program.add_to_running - Item Life Is Hot in Cracktown started running section program.run`

**Comment by Gaisberg** [comment]
Please find the item via the get_items endpoint and post the data.

**Comment by deepvalu** [comment]
How do I do that

**Comment by dreulavelle** [comment]
No longer relevant / Fixed
