### ISSUE TITLE
Stuck in onboarding phase

### ISSUE THREAD

**Issue by habitual69** [rivenmedia/riven#585]
When I open the frontend for the first time, enter all the details, and click the "Save and Continue" button, the page does not refresh or move to the next step.

**Comment by dreulavelle** [comment]
did you set ORIGIN env to the ip/fqdn of the host that Riven is on?

**Comment by habitual69** [comment]
I am running on docker and the ORIGIN is set to http://localhost:3000

**Comment by habitual69** [comment]
This is my Docker compose yml


services:
  riven-frontend:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - "3600:3000"
    tty: true
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - ORIGIN=http://localhost:3000 # set to the url or ip where the frontend is hosted
      - BACKEND_URL=http://riven:8080

  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    ports:
      - "8088:8080"
    tty: true
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - RIVEN_FORCE_ENV=true
      - RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@riven-db/riven
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - /home/ubuntu/dcontainer/riven:/riven/data
      - /mnt:/mnt
    depends_on:
      riven_postgres:
        condition: service_healthy

  riven_postgres:
    image: postgres:16.3-alpine3.20
    container_name: riven-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    volumes:
      - ./riven-db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

**Comment by davidemarcoli** [comment]
@habitual69 Then you have to set the origin to your fqdn.
