### ISSUE TITLE
Library Path config Issue

### ISSUE THREAD

**Issue by Rojeshkhatri** [rivenmedia/riven#589]
I'm using the latest release and encountering an issue during the onboarding process. The library path exists in the system, and when entering the library path in the front end "save and continue" it shows an API error, preventing progress to the next step but it successfully write data in settings.Json. Here is the log from the backend container.

  File "/riven/src/program/settings/manager.py", line 34, in notify_observers
    observer()
  File "/riven/src/program/program.py", line 76, in initialize_services
    SymlinkLibrary: SymlinkLibrary(),
                    ^^^^^^^^^^^^^^^^
  File "/riven/src/program/libraries/symlink.py", line 14, in __init__
    self.initialized = self.validate()
                       ^^^^^^^^^^^^^^^
  File "/riven/src/program/libraries/symlink.py", line 32, in validate
    available_dirs: str = ", ".join(os.listdir(library_path))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/riven'
24-08-01 20:37:33 | 👾 API       | main.dispatch - GET / - 200 - 0.00s
24-08-01 20:38:03 | 👾 API       | main.dispatch - GET / - 200 - 0.00s
![image](https://github.com/user-attachments/assets/6ea5aa66-3822-4bfe-a510-36cc776a0dd5)

**Comment by dreulavelle** [comment]
But it doesnt exist to Riven. What does the compose look like? Did you create the path for /mnt/riven ? Because Riven doesnt create that parent dir, but it will create the children dirs that it needs inside of that library path.
