### ISSUE TITLE
Option to trash torrents without resolution

### ISSUE THREAD

**Issue by davidemarcoli** [rivenmedia/riven#592]

**Comment by dreulavelle** [comment]
I figured for these types of scenario's, I'll either make it it's own setting, or tie it to a "strict" option people can set.

**Comment by davidemarcoli** [comment]
I would make it it's own setting, something like `trash_without_resolution`

**Comment by dreulavelle** [comment]
I'll add this with the next update for RTN. :)

Closing, as its planned.
