### ISSUE TITLE
[Feature] support for jellyfin

### ISSUE THREAD

**Issue by that-9uy** [rivenmedia/riven#594]
Adding updater for jellyfin.

**Comment by that-9uy** [comment]
I temporarily add this to my [local.py](https://github.com/rivenmedia/riven/blob/main/src/program/updaters/local.py).


```
    def refresh_jellyfin_library(self):
        url = "http://jellyfin:8096"
        token = ""

        curl_command = [
            "curl", "-X", "POST",
            f"{url}/Library/Refresh",
            "-H", "Content-Type: application/json",
            "-H", f"Authorization: MediaBrowser Token=\"{token}\"",
            "-v"
        ]

        try:
            result = subprocess.run(curl_command, capture_output=True, text=True)
            if result.returncode == 0:
                logger.log("JELLYFIN", "Successfully sent library refresh request to Jellyfin.")
            else:
                logger.error(f"Failed to refresh Jellyfin library. Return code: {result.returncode}, Output: {result.stderr}")
        except Exception as e:
            logger.error(f"Error occurred when trying to send library refresh request to Jellyfin. {e}")
```

**Comment by mysteryman69** [comment]
Apologies for dumb questions in the bug fix area...but I was looking into using jellyfin and I read riven wasn't compatible but no details of why. Is the auto update the only reason or is it something more in depth? I could add that code snippet, if it works but I am not sure if thats fix 1 of 5 things that are broken or a complete fix

**Comment by AyushSehrawat** [comment]
> Apologies for dumb questions in the bug fix area...but I was looking into using jellyfin and I read riven wasn't compatible but no details of why. Is the auto update the only reason or is it something more in depth? I could add that code snippet, if it works but I am not sure if thats fix 1 of 5 things that are broken or a complete fix

Jellyfin currently works with "automatic library scan" option. @dreulavelle is working on to add partial scans in it too

**Comment by AyushSehrawat** [comment]
> > Jellyfin currently works...
> 
> So it can be added to README in some way form or another? Is it supported?

Will be mentioned once support for partial scan in jf/emby is implemented because the caveat with automatic library  scan / realtime library scan is that if rd goes down, your whole library will be empty and scanned again when rd is up
