### ISSUE TITLE
[Bug] Endless SymLink Loop

### ISSUE THREAD

**Issue by frizat82** [rivenmedia/riven#615]
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:19 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:19 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program._process_future_item - Service Symlinker finished running on It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:19 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:19 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program._process_future_item - Service Symlinker finished running on It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:19 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:19 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program._process_future_item - Service Symlinker finished running on It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:19 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:19 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program._process_future_item - Service Symlinker finished running on It's Always Sunny in Philadelphia S15
24-08-12 18:04:19 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section program.run
24-08-12 18:04:19 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:19 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:20 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:20 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:20 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:20 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:20 | 🤖 PROGRAM   | program._process_future_item - Service Symlinker finished running on It's Always Sunny in Philadelphia S15
24-08-12 18:04:20 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section program.run
24-08-12 18:04:20 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section Symlinker
24-08-12 18:04:20 | 🤖 PROGRAM   | program._submit_job - Submitting service Symlinker to the pool with It's Always Sunny in Philadelphia S15
24-08-12 18:04:20 | 🔗 SYMLINKER | symlink._symlink_season - Symlinked all episodes for It's Always Sunny in Philadelphia S15
24-08-12 18:04:20 | 🤖 PROGRAM   | program._remove_from_running_items - Item It's Always Sunny in Philadelphia S15 finished running section Symlinker
24-08-12 18:04:20 | 🔍 DISCOVERY | program._push_event_queue - Re-added It's Always Sunny in Philadelphia S15 to the queue
24-08-12 18:04:20 | 🤖 PROGRAM   | program.add_to_running - Item It's Always Sunny in Philadelphia S15 started running section program.run
24-08-12 18:04:20 | 🤖 PROGRAM   | program._process_future_item - 

seems to just run endlessly

**Comment by dreulavelle** [comment]
fixed
