### ISSUE TITLE
[Bug] Wrong anime categorization for anime movies

### ISSUE THREAD

**Issue by rybertm** [rivenmedia/riven#672]
## Expected Behavior
Anime movies being correctly categorized as such

## Actual Behavior
Being wrongly categorized

## Steps to Reproduce the Problem

  1. Create separate libraries for Anime Shows/Anime Movies/Shows/Movies
  2. Make a request (I used overseerr) to an anime movie
  3. Check where the movie was imported to/DB entry

## Specifications

  - Version: [0355e64](https://github.com/rivenmedia/riven/commit/0355e6485c6e43f66a04165a85a890aaf1d8c0c3)
  - Platform: Ubuntu 22.04 (x64 and aarch64)
  - Summary (only available/green):
      * Core Services: 
          - `Symlink Library`
          - `Symlink`
          - `Scraping`
          - `Updater`
      * Downloader services:
          - `Real Debrid`
      * Content services: 
          - `Overseerr`
      * Scraping services: 
          - `Torrentio`

**Comment by dreulavelle** [comment]
can you show me the db entry or any log messages for this? I'm not seeing issues with this 🤔

**Comment by rybertm** [comment]
With a [Demon Slayer movie](https://www.imdb.com/title/tt11032374/) and this logger in place at [`program/indexers/trakt.py:`](https://github.com/rivenmedia/riven/blob/01e71f021643348dc7dddc4b172cf0ecb548342d/src/program/indexers/trakt.py#L76).
```py
        logger.debug(f"Input item before copy: {in_item.log_string} | Genres: {in_item.genres} | Anime: {in_item.is_anime}")
        logger.debug(f"Indexed item before copy: {item.log_string} | Genres: {item.genres} | Anime: {item.is_anime}")
        item = self.copy_items(in_item, item)
        logger.debug(f"Input item after copy: {in_item.log_string} | Genres: {in_item.genres} | Anime: {in_item.is_anime}")
        logger.debug(f"Indexed item after copy: {item.log_string} | Genres: {item.genres} | Anime: {item.is_anime}")
```

The following happens:
```log
24-09-01 17:08:57 | 🐞 DEBUG     | trakt.run - Input item before copy: tt11032374 | Genres: [] | Anime: False
24-09-01 17:08:57 | 🐞 DEBUG     | trakt.run - Indexed item before copy: Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train | Genres: ['anime', 'action', 'adventure', 'fantasy', 'thriller'] | Anime: True
24-09-01 17:08:57 | 🐞 DEBUG     | trakt.run - Input item after copy: tt11032374 | Genres: [] | Anime: False
24-09-01 17:08:57 | 🐞 DEBUG     | trakt.run - Indexed item after copy: Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train | Genres: ['anime', 'action', 'adventure', 'fantasy', 'thriller'] | Anime: False
24-09-01 17:08:57 | 🐞 DEBUG     | trakt.run - Indexed IMDb id (tt11032374) as Movie: Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train
```
Note that the "`Indexed item`" is what gets returned, hence the wrong classification.

**Comment by dreulavelle** [comment]
ahh yes, was able to test.. and indeed you are correct haha
