### ISSUE TITLE
Standalone errors.

### ISSUE THREAD

**Issue by 03184** [rivenmedia/riven#679]
Trying to install outside of docker and noticed in docs there was nothing about cloning the front end although the first command is "cd frontend". That aside once cloned frontend NPM is throwing up the following error, seems dependancy sunsetted.

me@riven:~/riven/riven/frontend# npm install
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for kysely@0.27.4: wanted: {"node":">=14.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm ERR! notsup Not compatible with your version of node/npm: kysely@0.27.4
npm ERR! notsup Not compatible with your version of node/npm: kysely@0.27.4
npm ERR! notsup Required: {"node":">=14.0.0"}
npm ERR! notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-09-01T12_30_30_454Z-debug.log

**Comment by AyushSehrawat** [comment]
`npm ERR! notsup Unsupported engine for kysely@0.27.4: wanted: {"node":">=14.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})`

You are using old node engine, it required 18+, and 20+ is preferred

Install pnpm (https://pnpm.io/) and then run `pnpm env use --global lts`

Then run `pnpm install` to install dependencies. Non docker is only recommended for testing
