### ISSUE TITLE
[Bug] Downloader ignoring torrents with multi-episode files

### ISSUE THREAD

**Issue by FlashLightning67** [rivenmedia/riven#684]
After the RD refactor, torrents that have multiple episodes in a file have been blacklisted even though they have all the needed episodes. I believe the issue is with line 20 of downloaders/shared.py: 

`if not needed_media or len(container) >= len([episode for season in needed_media for episode in needed_media[season]]):`

The check for if the container has more files than the amount of needed episodes doesn't account for if there are multiple episodes in a single file, so it skips those torrents.

**Comment by Gaisberg** [comment]
This should be fixed with v0.17
