### ISSUE TITLE
Riven downloading duplicate movies/series

### ISSUE THREAD

**Issue by kubo6472** [rivenmedia/riven#716]
View from DMM
![image](https://github.com/user-attachments/assets/f7487f99-e455-4fbf-9a8c-66ca2ba0cc4a)

Relevant part of the logs
![image](https://github.com/user-attachments/assets/56d1b7c8-b5e0-4b06-9ace-993565dc8b48)

[Complete logs](https://gist.githubusercontent.com/kubo6472/685af2e4427bd89ac36580439b2cee8e/raw/bd084e2ea22ee5146984764ea336cdfb0471d4c7/riven-20240922-2135.log)

[Config (redacted)](https://gist.githubusercontent.com/kubo6472/685af2e4427bd89ac36580439b2cee8e/raw/bd084e2ea22ee5146984764ea336cdfb0471d4c7/settings.json)

**Comment by dreulavelle** [comment]
This is bound to happen some with RD. Not necessarily a bug, just hard to really dial it in perfectly too. Their API is a pain in the ass to work with. We used to have duplicates in the higher single digits, or in some cases, double digits. I'll keep an eye on this.

Also, duplicates don't hurt anything either from what I've seen
