### ISSUE TITLE
Issue upgrading from .11.1 to any newer version

### ISSUE THREAD

**Issue by menmen01** [rivenmedia/riven#724]
Container crashes with this error 
```

Generating /riven/data/alembic/2024_09_24_028a2dea708d_auto_upg_20240924012158.py ...  done
24-09-24 01:21:59 | ⚠️  WARNING   | db.run_migrations - Error running migrations: (psycopg2.errors.UndefinedObject) type "states" does not exist
[SQL: ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states ]
(Background on this error at: https://sqlalche.me/e/20/f405)
Generating /riven/data/alembic/2024_09_24_061ced26fc2e_auto_upg_20240924012200.py ...  done
24-09-24 01:22:01 | ⚠️  WARNING   | db.run_migrations - Error running migrations: (psycopg2.errors.UndefinedObject) type "states" does not exist
[SQL: ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states ]
(Background on this error at: https://sqlalche.me/e/20/f405)
24-09-24 01:22:01 |  CRITICAL  | main.<module> - Server has been stopped

```

Downgrading allows the container to start

Present on all releases .12 and up 

Not the same issue as #722

**Comment by dreulavelle** [comment]
Thats normal. I mentioned this is an announcement in our Discord that from 0.11.x to 0.12.x needs to have a database reset and their settings file deleted so that Riven can recreate everything. There was a **A LOT** that changed!

**Comment by dreulavelle** [comment]
Don't worry, it will all get reindexed in :)

**Comment by profucius** [comment]
> I mentioned this is an announcement in our Discord

Is there another location that announcements could be made for things like this? Perhaps as a bold header at the top of the github release notes? I struggle with managing all the discords and notifications it brings, but github releases would help me catch things like this quicker.

**Comment by dreulavelle** [comment]
https://discord.com/channels/1148672013028831352/1199500061151871006/1286779573341520016

But you would of had to of been in the server already when it came out. If I need users to do another reset in the future, I can include it in the release notes though
