### ISSUE TITLE
[Feature request] Optionally delete Overseerr request upon deletion

### ISSUE THREAD

**Issue by filiptrplan** [rivenmedia/riven#731]
It would be great to have an option to delete the associated Overseerr request when deleting a show from the library. Currently you first have to remove the request in Overseerr, then remove the show in Riven, else it gets added back to Riven.

**Comment by dreulavelle** [comment]
We send the delete request to Overseerr on removal already

**Comment by filiptrplan** [comment]
Sorry, then it should be a configuration issue on my part.

**Comment by dreulavelle** [comment]
The data gets lost on database resets. That could possibly be it too.
