### ISSUE TITLE
[Feature Request] Sync lists to playlist

### ISSUE THREAD

**Issue by subvhome** [rivenmedia/riven#742]
Hey, I’ve got a request for Riven—would it be possible to add functionality where, when a Trakt user list is configured and Riven pulls that media, it automatically creates a playlist in Plex with the same name as the list? So for example, if I have a Trakt list called "Favorites" and Riven downloads those titles, it would create a corresponding "Favorites" playlist in Plex with that content.

This would make things a lot smoother for organizing media. Let me know if that’s something that could be added! Thanks!

**Comment by dreulavelle** [comment]
https://kometa.wiki/en/latest/files/playlists/

;)
