### ISSUE TITLE
Mac docker /mnt issue

### ISSUE THREAD

**Issue by bryshaw** [rivenmedia/riven#779]
Hello,

I cannot run riven on Mac docker desktop due to an issue where docker can’t see /mnt as a path due to there being no /mnt in macOS.

**Comment by AyushSehrawat** [comment]
> Hello,
> 
> I cannot run riven on Mac docker desktop due to an issue where docker can’t see /mnt as a path due to there being no /mnt in macOS.

You can use any path, /mnt is not necessary. Just make sure to do the mappings correctly in all configs

**Comment by bryshaw** [comment]
Which configs to be sure? Also, do I remove the - /mnt: portion from the config?

**Comment by AyushSehrawat** [comment]
Plex and riven mainly.

Also few things to note,

The path of median mount on host machine should be same in plex docker

Like if your mount are in /home/bryshaw/mount then it should be `/home/bryshaw/mount:/home/bryshaw/mount`

Requires for symlink to resolve inside Docker
