### ISSUE TITLE
Getting error's and Riven container keeps stopping on latest front/backend 16.2/16.3

### ISSUE THREAD

**Issue by Tw1zT3d2four7** [rivenmedia/riven#820]
Getting error's and Riven container keeps stopping on latest front/backend 16.2/16.3. this setup has ran perfect then all of a sudden these errors? nothing has changed or been changed.
[_riven_logs.txt](https://github.com/user-attachments/files/17530777/_riven_logs.txt)
[_riven-db_logs.txt](https://github.com/user-attachments/files/17530785/_riven-db_logs.txt)

**Comment by davidemarcoli** [comment]
Please update to the newest version and open a new issue if it happens again.
