### ISSUE TITLE
/onboarding displays upon every time accessing UI

### ISSUE THREAD

**Issue by bioengineered** [rivenmedia/riven#829]
Any time I access the web UI at http://ip-address:3000, Riven attempts to begin the first time setup process.
All of the values displayed are correct (as they are in the compose file.)

Upon checking the logs, this bit seems potentially relevant:
![image](https://github.com/user-attachments/assets/8f63e1bf-94e0-421d-b4c9-47777a7e0f8d)

Here is my current docker compose: https://pastebin.com/Y36UWWyh

**Comment by davidemarcoli** [comment]
Can you please send the full logs before the snippet in the screenshot? Thank you!

**Comment by bioengineered** [comment]
Here are the full logs:
https://pastebin.com/iXuRi61Y

**Comment by davidemarcoli** [comment]
The rclone path `/mnt/zurg/__all__` doesn't seem to exist. Have you mounted it to the riven container?

**Comment by bioengineered** [comment]
Seems to have fixed the issue!
However, now my logs are being flooded with the same error:
![image](https://github.com/user-attachments/assets/c022561a-6d06-413e-928f-de7921b3130a)

My initial thoughts were that it may be a permissions issue. When attempting to edit the permissions, I get this error:
cannot read directory '/mnt/library/movies/Cheaper by the Dozen 2 (2005) {imdb-tt0452598}': Input/output error

Full log: https://pastebin.com/TCjydCzk

**Comment by davidemarcoli** [comment]
What are your rclone/library paths now? Rclone `/mnt/zurg/__all__` and Library `/mnt/library`?

**Comment by bioengineered** [comment]
Rclone path was set to /mnt/Library/__all__
Library was /mnt/library

Updated Rclone path in both Zurg config and Riven config to /mnt/zurg/__all__ and it seems to have resolved the issue.

Thanks for helping me out with this one.
Still trying to learn the ropes.
