### ISSUE TITLE
Torbox Search missing required API key/NZB support

### ISSUE THREAD

**Issue by s1dave-web** [rivenmedia/riven#866]
Torbox search is an option that can be enabled but provides no section for the API key which is required to search for data.

Does Riven have the ability to support Torbox & Prowlarr searching and grabbing NZB files for the usenet download feature?

**Comment by s1dave-web** [comment]
Suspect the Torbox API switched to requiring the API key for grabbing data as I had to update the Prowlarr custom integration to include the API key in the header:
search:
  headers:
    Authorization: ["Bearer {{ .Config.apikey }}"]

**Comment by jopsis** [comment]
![image](https://github.com/user-attachments/assets/3efa5901-40cb-4705-acde-b6497863808b)

Inside settings.json on /riven/data can you activate and set your api-key for torbox

**Comment by davidemarcoli** [comment]
@s1dave-web Please try the solution proposed by jopsis. If you still encounter the issue, please re-open the ticket.
