### ISSUE TITLE
Add Support for Spanish Latin American (es-MX) Language Code

### ISSUE THREAD

**Issue by Carlosjrlu** [rivenmedia/riven#867]
### Description:
I've successfully set up Riven with Plex, and everything is working smoothly. However, I encountered a limitation in the language ranking settings. My goal is to prioritize movies in Spanish Latin American (LATAM) language, but the ISO 639-1 language codes used in Rank Torrent Name don't include an option for it.

### Problem:
Currently, the language ranking system only supports the general Spanish code (es), which defaults to Spanish from Spain. When using the es code, Riven prioritizes English movies if the available Spanish audio is only in the LATAM variant. This prevents users from accessing Spanish LATAM content as the preferred language.

### Example:
Here Riven preffered a portuguese movie.
![image](https://github.com/user-attachments/assets/e541b4dd-2b6d-4047-a4da-b2554b3acdbb)

### Request:
Would it be possible to add support for the es-MX language code in Riven's ranking options? This would greatly enhance the experience for users who prefer Spanish LATAM content.

Thank you!

**Comment by dreulavelle** [comment]
Downloading has nothing to do with ranking. It just goes down the list of returned torrents from scrapers after they've been sorted. So either the first one wasn't cached or didnt have the file we wanted, so it moves to the 2nd one in the list, and in this case, it had what we wanted and it was cached.

This isnt a language issue, nor any issue. It did what it's supposed to :)

**Comment by Carlosjrlu** [comment]
In this case it went for the 4th option. Btw, could you help me with a discord invite link, the one in the Readme doesn't work.
https://discord.com/invite/rivenmedia <- This one is not valid anymore.

**Comment by dreulavelle** [comment]
https://discord.gg/rivenmedia :)

I wonder if we lost our boosting status briefly so it went away, thats strange!
