### ISSUE TITLE
Overseerr Webhook Not Working

### ISSUE THREAD

**Issue by herbhuang** [rivenmedia/riven#889]
I followed the instruction creating Overseerr notification. However, I failed in testing webhook from overseerr. I am aware of #471 however I had specified the backend.

Not sure if it is anything regarding API url.
```
24-11-17 23:43:49 | 👾 API       | main.dispatch - GET /api/v1/items - 200 - 0.04s
24-11-17 23:43:49 | 👾 API       | main.dispatch - GET /api/v1/items - 200 - 0.04s
24-11-17 23:43:49 | 👾 API       | main.dispatch - GET / - 404 - 0.00s
24-11-17 23:43:51 | 👾 API       | main.dispatch - POST /webhook/overseerr - 404 - 0.00s
24-11-17 23:43:57 | 👾 API       | main.dispatch - POST /api/v1/webhook/overseerr - 401 - 0.00s
```

**Comment by davidemarcoli** [comment]
You have to add the Authentication header to the config in overseerr.
![image](https://github.com/user-attachments/assets/9181a097-8598-46e0-8f4f-43e6e9b2530b)
You find the api key in the settings.

**Comment by herbhuang** [comment]
Thank you! I implemented and it works! Is there an updated version of wiki/instruction that I should refer to?

**Comment by davidemarcoli** [comment]
@herbhuang The wiki isn't updated yet unfortunately. But I'll try to update it this week!
