### ISSUE TITLE
Error deleting media in riven requested by Overseerr

### ISSUE THREAD

**Issue by ratchettest** [rivenmedia/riven#891]
24-11-18 09:34:53 | ❌ ERROR     | main.dispatch - Exception during request processing: type object 'Overseerr' has no attribute 'delete_request'

This happens when I go to delete media inside of riven that was initially requested by Overseerr. 
Looks like part of the media is removed as the files disappear from Plex but the media then remains stale and broken inside of riven.

**Comment by GSKang94** [comment]
Seems like it got fixed in the last update

**Comment by dreulavelle** [comment]
yeah, I fixed this error in the last update. :)
