### ISSUE TITLE
Error real debrid: failed to get instant availabilty

### ISSUE THREAD

**Issue by fexd12** [rivenmedia/riven#908]
Hi!

I'm getting this error whene trying to download from real debrid:  Failed to get instant availability.

Maybe real debrid changed his api, since i don't find this path on his api docs.
https://api.real-debrid.com/

24-11-24 03:56:05 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 3/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/8a79bc94acdc5f0b8da442fd0e0686dd0e6548a6
24-11-24 03:56:05 | 🐞 DEBUG     | realdebrid.get_instant_availability - All retry attempts failed for instant availability
24-11-24 03:56:05 | 🐞 DEBUG     | __init__.run - Invalid stream: 8a79bc94acdc5f0b8da442fd0e0686dd0e6548a6 - reason: Not cached!
24-11-24 03:56:05 | 🐞 DEBUG     | item.blacklist_stream - Blacklisted stream 8a79bc94acdc5f0b8da442fd0e0686dd0e6548a6 for Next Stop, Christmas
24-11-24 03:56:05 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 1/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/9406766ddf236ecc6d11a83d3cc733439d5662bf
24-11-24 03:56:07 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 2/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/9406766ddf236ecc6d11a83d3cc733439d5662bf
24-11-24 03:56:08 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 3/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/9406766ddf236ecc6d11a83d3cc733439d5662bf
24-11-24 03:56:08 | 🐞 DEBUG     | realdebrid.get_instant_availability - All retry attempts failed for instant availability
24-11-24 03:56:08 | 🐞 DEBUG     | __init__.run - Invalid stream: 9406766ddf236ecc6d11a83d3cc733439d5662bf - reason: Not cached!
24-11-24 03:56:08 | 🐞 DEBUG     | item.blacklist_stream - Blacklisted stream 9406766ddf236ecc6d11a83d3cc733439d5662bf for Next Stop, Christmas
24-11-24 03:56:08 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 1/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/13943e13c5bb6277cde4b69fb6be3b57a910a8ee
24-11-24 03:56:10 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 2/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/13943e13c5bb6277cde4b69fb6be3b57a910a8ee
24-11-24 03:56:11 | 🐞 DEBUG     | realdebrid.get_instant_availability - Failed to get instant availability (attempt 3/3): Request failed: 403 Client Error: Forbidden for url: https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/13943e13c5bb6277cde4b69fb6be3b57a910a8ee
24-11-24 03:56:11 | 🐞 DEBUG     | realdebrid.get_instant_availability - All retry attempts failed for instant availability

Thanks in advance.

**Comment by dhumphrey7** [comment]
real-debrid has removed the instantAvailability endpoint from their API.  The the devs work, as they find solutions to a problem that was dropped instantly in their laps.
