### ISSUE TITLE
[Feature Request] Ignore List

### ISSUE THREAD

**Issue by deepvalu** [rivenmedia/riven#99]
Would be nice to have the ability to have an ignore list where items get added after x attempts or can be manually added. Could be controlled from the front end. Maybe ability to add items by dynamic search/imdb id.

**Comment by dreulavelle** [comment]
ignore list based off id sounds interesting @Gaisberg

**Comment by AyushSehrawat** [comment]
> Would be nice to have the ability to have an ignore list where items get added after x attempts or can be manually added. Could be controlled from the front end. Maybe ability to add items by dynamic search/imdb id.

Sounds good! Frontend can have ability to edit ignore file too and in future ability to manually scrape too.

@dreulavelle Since scraping with cinemeta/trakt will give necessary stuff, backend will need to have some changes to support downloading & symlinking with it

**Comment by dreulavelle** [comment]
Funny enough.. I added this a while back.. but then recently removed it, and then someone complained about it missing. lol 😂 

I'll add it back! :)
